### 错误 调试 测试
####错误处理
*try...expect..finally..*
>
    try:
        print('try..')
        r=10/0
        print('result',r)
    expect ZeroDivisionError as e:
        print('expect',e)
    except ValueError as e:
        print('ValueError:'.e)
    finally:
        print('finally)

*可以多类型错误捕获*
**注意错误类型继承自BaseException 要注意其他错误类型的子类 出现重复时不会捕获**
>
    try:
        foo()
    except ValueError as e:
        print('ValueError')
    except UnicodeError as e:
        print('UnicodeError') 
#### 调用栈
*如果错误没有被捕获,它就会一直向上抛出*
#### 记录
>
    import logging
*将错误记录在logging中*
#### 自定义
>  
    class FooError(valueError):
        pass

    def foo(s):
        n=int(s)
        if n==0:
            raise FooError('invalid value:%s' %s)
        return 10/n
*自定义的错误 推荐尽量使用内置错误类型*

